### ISSUE TITLE
Add new command to review structure of commits on branch

### ISSUE THREAD

**Issue by mcampbell508** [mcampbell508/git-review#7]
This will be designed to review commits so that they follow "good commit message guidelines" as outlined here

https://chris.beams.io/posts/git-commit/

Command name could possibly be `review:commits`

Possible options:

```
reviews:
  commits:
    recommended_max_commits: 10
    subject:
      max_length: 60
      capitalised: true
      no_full_stop: true
      imperative_check: true
      prefix_regex: ""
    body:
      wrapped_line_length: 72
      recommended_min_characters: 30 # use to explain the why behind a commit's existence
      issue_reference_regex: ""
```
