### ISSUE TITLE
Add new command to review branch naming

### ISSUE THREAD

**Issue by mcampbell508** [mcampbell508/git-review#8]
This will be designed to review branch names against options that can be provided via the `git-review.yml.dist` file.

Command name could possibly be `review:branch`

Possible options could include:

```
reviews:
  branch:
    min_length: 10
    max_length: 40
    prefix_regex: "" #branches should start with issue number or type of change I.e feature
```
